name: my_books_to_read
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.development
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

flutter_intl:
  enabled: true
  main_locale: en

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  any_animated_button: 0.0.4
  bot_toast: 4.1.3
  cached_network_image: 3.3.0
  cloud_firestore: 4.13.1
  cupertino_icons: 1.0.6
  dartz: 0.10.1
  device_info_plus: 9.1.1
  dio: 5.3.3
  enum_to_string: 2.0.1
  equatable: 2.0.5
  fimber: 0.7.0
  firebase_core: 2.22.0
  firebase_crashlytics: 3.4.4
  fluro: 2.0.5
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  intl: 0.18.1
  json_annotation: 4.8.1
  pretty_dio_logger:
    git:
      url: https://github.com/appvinio/pretty_dio_logger.git
  rxdart: 0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.6
  json_serializable: 6.7.1
  flutter_launcher_icons: 0.13.1
  freezed: 2.4.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/jpg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
